signin / onboarding / mixsearch 페이지 작업
mash-up-kr/AllNight-iOS pull request #2
Opened 2019-06-29 21:40 UTC by JSpiner

- signin
- onboarding
- mixsearch
페이지 작업 완료하였습니다.

2019-07-01 05:18 UTC, OhKanghoon requested changes

2019-07-01 05:18 UTC, OhKanghoon commented on allnight-ios/Souces/Utils/BaseUIViewController.swift
> +import Foundation
사용하지 않는 파일은 제거해주세요

2019-07-01 05:18 UTC, OhKanghoon commented on allnight-ios/Souces/Domain/Sign In/SignInViewController.swift
> +    // MARK: View LifeCycle
MARK: 는 아래 `viewdidload` 위로 옮겨주세요

2019-07-04 10:24 UTC, JSpiner commented on allnight-ios/Souces/Domain/Sign In/SignInViewController.swift
> +    // MARK: View LifeCycle
d0fb76d0b46cc3961ff159f0432205fe828021d5 에서 옮겼습니다

2019-07-04 10:25 UTC, JSpiner commented on allnight-ios/Souces/Utils/BaseUIViewController.swift
> +import Foundation
졸다가 잘못추가했네요 😅 
09965f7e2c8d8d4dba243c259ee0350d11d870c6 에서 제거했습니다.

2019-07-04 10:56 UTC, OhKanghoon approved these changes

2019-07-04 10:56 UTC, merged