Detail Recipe view 완료
mash-up-kr/AllNight-iOS pull request #4
Opened 2019-07-12 09:31 UTC by SujiKim6

- color sets 추가
- 글꼴 추가
- Detail_recipe 화면 작업 완료

(추후 서버 부분 추가 필요)

2019-07-12 12:49 UTC, JSpiner reviewed
스토리보드는 제 힘으로 리뷰하기 힘들어서 .swift 코드만 리뷰했습니다. 🙏

2019-07-12 12:49 UTC, JSpiner commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +    private func initTableView() {
함수의 호출 순서에따라 `initTableView()`가 `viewDidLoad()` 바로 밑으로 간다면 더 읽기 좋을것같아요
(약한제안입니다.)

2019-07-12 12:49 UTC, JSpiner commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        if scrollView.contentOffset.y == -387.0 {
이곳과 [#L132](https://github.com/mash-up-kr/AllNight-iOS/pull/4/commits/3be74dde4a64783ee6d8274243997409d2e0333e#diff-9d636713551156e0f9a829c529028621R132) 에서 `-387.0` `0.2` 매직넘버가 쓰이고있는데
의미를 부여한 상수로 빼는게 좋을것같아요

2019-07-12 12:49 UTC, JSpiner commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +    func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
- scrollViewDidEndDragging
- scrollViewDidEndDecelerating

위 두 함수는 호출하는곳이 없는데 필요한가요?

2019-07-12 12:49 UTC, JSpiner commented on allnight-ios/Resources/Assets.xcassets/normal.imageset/Contents.json
> +      "filename" : "normal.png"
`icCircle.png`과 `normal.png` 간에 네이밍 통일이 필요할것같아요

2019-07-12 12:49 UTC, JSpiner commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        let isScrollingUp = scrollDiff > 0 && scrollView.contentOffset.y + scrollView.contentInset.top > absoluteTop
`absoluteTop`의 값은 항상 0인데요. 상수로 빼내는건 어떨까요?

2019-07-12 22:54 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        if scrollView.contentOffset.y == -387.0 {
이 곳에 있는 -387.0은 현재 최종 코드에는 지운 라인이고, 말씀해주신 0.2는 의미를 부여한 상수로 뺐습니다.
605ac2f4a859e027d8ff0402487490617a263ad1 에 반영했습니다:)

2019-07-12 22:54 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +    func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
이 부분은 tableview를 움직일때 호출이 되는 함수이어서, 필요한 코드 입니다.

2019-07-12 22:55 UTC, SujiKim6 commented on allnight-ios/Resources/Assets.xcassets/normal.imageset/Contents.json
> +      "filename" : "normal.png"
normal.png를 icStar.png로 네이밍 통일했습니다 (68b3efdfafcef1cffa507fc93aa58eafa1382314)

2019-07-12 22:56 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        let isScrollingUp = scrollDiff > 0 && scrollView.contentOffset.y + scrollView.contentInset.top > absoluteTop
이 부분도 상수로 따로 상단에 빼두었습니다 =) 605ac2f4a859e027d8ff0402487490617a263ad1

2019-07-12 22:57 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +    private func initTableView() {
605ac2f4a859e027d8ff0402487490617a263ad1 안 그대로 위치 부분을 어떻게 할지 고민하고 있었는데, 제안을 받아들여 위치를 바로 밑으로 옮겼어요!

2019-07-13 02:22 UTC, JSpiner approved these changes
LGTM 👍 👍 👍 
수고 많으셨습니다!

2019-07-13 06:35 UTC, OhKanghoon requested changes

2019-07-13 06:35 UTC, OhKanghoon commented on allnight-ios/Souces/Domain/Recipe/DetailInformationTableViewCell.swift
> +    func config(title: String, detail: String) {
`config` 가 의미하는 바는 따로 있습니다.
`configure` 라는 정확한 이름을 쓰는게 좋아보여요

2019-07-13 06:35 UTC, OhKanghoon commented on allnight-ios/Souces/Domain/Recipe/RecipeRowTableViewCell.swift
> +    func config() {
여기도 `configure`

2019-07-13 06:42 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeRowTableViewCell.swift
> +    func config() {
334b17c2382e9406e466c3b9fc16597fb299588b 수정했습니다:)

2019-07-13 06:42 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/DetailInformationTableViewCell.swift
> +    func config(title: String, detail: String) {
334b17c2382e9406e466c3b9fc16597fb299588b 수정했습니다:)

2019-07-13 06:47 UTC, KiWooyoung commented on allnight-ios/Resources/Assets.xcassets/normal.imageset/Contents.json
> +      "filename" : "normal.png"
우리나라는 통일이 되나요?

2019-07-13 06:49 UTC, kor-Chipmunk approved these changes
👍👍👍👍👍👍👍👍👍 코멘트 한 부분은 급한 수정이 아니라서 찬찬히 해도 될 것 같아용

2019-07-13 06:49 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +            print(abs(scrollDiff))
print() 문은 푸쉬할 때 주석처리하는게 좋을 것 같습니다!

2019-07-13 06:49 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +                print(headerHeightConstraint.constant)
요기도 확인!

2019-07-13 06:49 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        self.isAnimating = true
self 를 쓰지 않아도 될 때는 생략하는 편이 더 좋을 것 같습니다!

2019-07-13 06:49 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        print(scrollViewMaxHeight)
print() 확인!

2019-07-13 06:52 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +            print(abs(scrollDiff))
신기한게 옛날에 작업한게 계속 뜨네용... 이건 제가 헤더부분 만들면서 봤던건데 지운거에요! ㅜㅜ

2019-07-13 06:52 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +                print(headerHeightConstraint.constant)
이것도 마지막 파일에는 지웠어요!

2019-07-13 06:53 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        print(scrollViewMaxHeight)
이 부분도 최신 소스 파일에는 없지만.. 왜 계속 이렇게 뜨는 걸까용...?(의문)

2019-07-13 06:55 UTC, SujiKim6 commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        self.isAnimating = true
e2b6d82cca934d06e28df4dfb519e27ca80f391e 생략 완료했습니다:)

2019-07-13 06:55 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +            print(abs(scrollDiff))
앗 그렇군요. 제가 옛날 커밋 봐서 그런것같아요!

2019-07-13 06:59 UTC, kor-Chipmunk commented on allnight-ios/Souces/Domain/Recipe/RecipeViewController.swift
> +        self.isAnimating = true
확인했습니다!

2019-07-13 10:09 UTC, OhKanghoon approved these changes

2019-07-13 10:09 UTC, merged